### ISSUE TITLE
📦 Acquire Custom Domain Name

### ISSUE THREAD

**Issue by alextakahashi** [MadeInChinatown/Preparedness#19]
Part of the Giphy Brand Requirement is that we must have an email with our custom domain name.  We need to be a brand in order for our Gifs to be searchable on Instagram

> Brands are required to use an email address with a company domain that matches the applying username, ex: jane@username.com.

I was able to find this domain through [Google Domains](https://domains.google/?gclid=EAIaIQobChMI4oCD3bzC6AIVFtVkCh2PrgnOEAAYASAAEgIc3vD_BwE).  Only $12 / year

```
madeinchinatownsf.com
```

References:
* [Tips for Submitting An Application](https://support.giphy.com/hc/en-us/articles/360020433711-Essential-Tips-For-Submitting-A-Brand-or-Artist-Application-)

**Comment by nogithubplz** [comment]
Rosa created domain and suite for email. If more names and email is needed do tell so Rosa can create.
