### ISSUE TITLE
Task Migration to Github Issues

### ISSUE THREAD

**Issue by alextakahashi** [MadeInChinatown/Preparedness#7]
## Pros:
* 🏔 Clear ownership of tasks
* 📈 Can post updates in the comments BEFORE the meeting
* 👀 Better Transparency of what is on our plates.

## Cons:
* 🛠 everyone needs to create a github account 😅 - its free! Plus you can see what it's like to be an engineer.  

Action Items - get everyone on github as an owner of this repo.
* [x] Alex
* [x] Sebastian 
* [x] Sam
* [ ] Judy
* [x] Lisa
* [x] Rosa
* [x] Sandy

**Comment by alextakahashi** [comment]
All tasks from the today's meeting have been migrated to github

**Comment by Lyu29** [comment]
Alex migrated the issues.
